# Generated by Django 5.1.6 on 2025-02-21 10:18

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Title for SEO (Max: 60 characters)', max_length=60, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='Description for SEO (Max: 160 characters)', max_length=220, null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords (Max: 10 keywords)', max_length=255, null=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='Megazine/Cover_images/')),
                ('cover_video', models.FileField(blank=True, null=True, upload_to='Magazines/Cover_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Magazine.category')),
                ('tags', models.ManyToManyField(blank=True, to='Magazine.tag')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='MagazineSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Title for SEO (Max: 60 characters)', max_length=60, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='Description for SEO (Max: 160 characters)', max_length=220, null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords (Max: 10 keywords)', max_length=255, null=True)),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('content_top', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/sections/images/')),
                ('image_caption', models.CharField(blank=True, max_length=255, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='articles/sections/videos/')),
                ('external_video_url', models.URLField(blank=True, null=True)),
                ('content_bottom', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('megazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Magazine.magazine')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
