# Generated by Django 5.1.6 on 2025-02-25 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magazine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='magazinesection',
            old_name='megazine',
            new_name='magazine',
        ),
        migrations.RemoveField(
            model_name='magazinesection',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='magazinesection',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='magazinesection',
            name='meta_title',
        ),
        migrations.AlterField(
            model_name='magazine',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='Magazines/Cover_images/'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Description for SEO (Max: 160 characters)', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='magazinesection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Magazines/sections/'),
        ),
        migrations.AlterField(
            model_name='magazinesection',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='Magazines/videos/'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('magazine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Magazine.magazine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
