# Generated by Django 5.1.6 on 2025-03-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Magazine",
            "0002_subscriber_rename_megazine_magazinesection_magazine_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact_Us",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("message", models.TextField()),
                ("subject", models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name="magazine",
            name="magazine_intro",
            field=models.TextField(blank=True, null=True),
        ),
    ]
