# Generated by Django 5.1.6 on 2025-03-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Magazine", "0003_contact_us_magazine_magazine_intro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magazine",
            name="magazine_intro",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
