# Generated by Django 5.1.6 on 2025-03-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Magazine", "0004_alter_magazine_magazine_intro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magazine",
            name="slug",
            field=models.SlugField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="magazine",
            name="title",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
