# Generated by Django 5.1.6 on 2025-03-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Magazine", "0005_alter_magazine_slug_alter_magazine_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magazine",
            name="author",
            field=models.CharField(max_length=250),
        ),
    ]
